version: '2'
services:
    mongo-2:
        container_name: "mongo-2"
        image: mongos_cluster
        network_mode: aim-mongo-cluster
        ports:
            - "31002:27017"
            - "32002:28017"
#        command: mongod --replSet aim-mongo --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        environment: 
            - replSet=aim-mongo
            - size=16
        volumes:
            - ../cluster/run.sh:/run.sh
        restart: always

    mongo-3:
        container_name: "mongo-3"
        image: mongos_cluster
        network_mode: aim-mongo-cluster
        ports:
            - "31003:27017"
            - "32003:28017"
#        command: mongod --replSet aim-mongo --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        environment: 
            - replSet=aim-mongo
            - size=16
        volumes:
            - ../cluster/run.sh:/run.sh
        restart: always 

    mongo-1:
        container_name: "mongo-1"
        image: mongos_cluster 
        network_mode: aim-mongo-cluster
        ports:
            - "31001:27017"
            - "32001:28017"
#        command: mongod --replSet aim-mongo --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        environment: 
            - replSet=aim-mongo
            - size=16
        volumes:
            - ../cluster/run.sh:/run.sh
        links:
            - mongo-2:mongo-2
            - mongo-3:mongo-3
        restart: always

    mongo-setup:
        container_name: "mongo-setup"
        image: mongos_cluster
        network_mode: aim-mongo-cluster
        depends_on:
            - "mongo-1"
            - "mongo-2"
            - "mongo-3"
        links:
            - mongo-1:mongo-1
            - mongo-2:mongo-2
            - mongo-3:mongo-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=47.95.248.121
            - MONGO2=47.95.248.121
            - MONGO3=47.95.248.121
            - PORT1=31001
            - PORT2=31002
            - PORT3=31003
            - RS=aim-mongo
        entrypoint: [ "/scripts/setup.sh" ]
